import { createHash } from "node:crypto";

/**
 * Where document bytes actually live, behind one interface with two
 * implementations — the same split, for the same reason, that src/lib/db.ts
 * makes between D1 and a local SQLite file.
 *
 *   Production (USE_D1 === "true", i.e. on Workers): the DOCUMENTS R2 bucket.
 *   Everywhere else (next dev, tests, scripts): a directory on disk.
 *
 * The local half exists because `next dev` runs in plain Node with no Workers
 * runtime and therefore no bindings at all. Without it the whole feature would
 * be undevelopable outside a deploy, which is precisely the trap db.ts avoids.
 *
 * Why R2 rather than a Bytes column, given MaintenancePhoto and ListingPhoto
 * both took the latter route: those hold photos, capped at 4 MB and rarely
 * near it. This holds scanned leases and inspection reports — tens of
 * megabytes each, hundreds per landlord — and D1 has a hard per-database size
 * ceiling that such a pile would consume outright. docs/ROADMAP.md already
 * tracks moving the two photo tables here for the same reason.
 *
 * Keys are opaque and organization-scoped: `<organizationId>/<random>`. The
 * org prefix makes "everything belonging to this org" a single R2 list
 * operation (useful for deletion and accounting), and the random suffix means
 * a key can never be guessed from a filename. Neither is an access control on
 * its own — reads are authorized per-request in the route, always.
 */

export type StoredObject = {
  key: string;
  contentHash: string;
  sizeBytes: number;
};

function onWorkers(): boolean {
  return process.env.USE_D1 === "true";
}

/**
 * Resolved lazily inside a request, never at module scope: on Workers the
 * binding simply does not exist at isolate cold-start, which is the same
 * constraint that forces db.ts to build its client behind a Proxy.
 */
function bucket(): R2Bucket {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { getCloudflareContext } = require("@opennextjs/cloudflare") as typeof import("@opennextjs/cloudflare");
  const { env } = getCloudflareContext();
  if (!env.DOCUMENTS) {
    throw new Error(
      "The DOCUMENTS R2 binding is missing. Check r2_buckets in wrangler.jsonc, and that the bucket exists in the account.",
    );
  }
  return env.DOCUMENTS;
}

/** Local-dev storage root. Gitignored; see .gitignore. */
function localRoot(): string {
  // Required lazily so bundling for Workers never pulls node:path/node:fs into
  // the Worker build through this module's top level.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const path = require("node:path") as typeof import("node:path");
  return path.join(process.cwd(), ".local-documents");
}

function localPathFor(key: string): string {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const path = require("node:path") as typeof import("node:path");
  // Keys are generated by this module and contain exactly one slash, but a
  // path is being built from one — refuse anything that could climb out of
  // the storage root rather than trusting that invariant holds forever.
  if (key.includes("..") || path.isAbsolute(key)) {
    throw new Error(`Refusing to resolve suspicious storage key: ${key}`);
  }
  return path.join(localRoot(), key);
}

export function storageKeyFor(organizationId: string): string {
  const random = crypto.randomUUID().replace(/-/g, "");
  return `${organizationId}/${random}`;
}

export function hashBytes(bytes: Uint8Array): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export async function putObject(args: {
  organizationId: string;
  bytes: Uint8Array;
  contentType: string;
}): Promise<StoredObject> {
  const key = storageKeyFor(args.organizationId);
  const contentHash = hashBytes(args.bytes);

  if (onWorkers()) {
    await bucket().put(key, args.bytes, {
      httpMetadata: { contentType: args.contentType },
    });
  } else {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("node:fs/promises") as typeof import("node:fs/promises");
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const path = require("node:path") as typeof import("node:path");
    const target = localPathFor(key);
    await fs.mkdir(path.dirname(target), { recursive: true });
    await fs.writeFile(target, args.bytes);
  }

  return { key, contentHash, sizeBytes: args.bytes.byteLength };
}

/** Null when the object is missing — a dangling row, not an exception worth throwing. */
export async function getObject(key: string): Promise<Uint8Array | null> {
  if (onWorkers()) {
    const object = await bucket().get(key);
    if (!object) return null;
    return new Uint8Array(await object.arrayBuffer());
  }

  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const fs = require("node:fs/promises") as typeof import("node:fs/promises");
  try {
    const buffer = await fs.readFile(localPathFor(key));
    return new Uint8Array(buffer);
  } catch {
    return null;
  }
}

/**
 * Best-effort: a storage delete that fails must not strand the database row,
 * because an orphaned row is a document the landlord can see and cannot get
 * rid of. Orphaned *bytes* are merely wasted space. Callers delete the row
 * regardless — the same trade-off disconnectBankAction makes when Plaid's
 * side of a disconnect fails.
 */
export async function deleteObject(key: string): Promise<void> {
  try {
    if (onWorkers()) {
      await bucket().delete(key);
      return;
    }
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const fs = require("node:fs/promises") as typeof import("node:fs/promises");
    await fs.unlink(localPathFor(key));
  } catch (err) {
    console.error("[documents] failed to delete stored object", key, err);
  }
}
