-- Generated by scripts/sync-d1-migrations.mjs from
--   prisma/migrations/20260821233209_add_tenant_screening/migration.sql
-- Do not edit this file. Edit prisma/schema.prisma and run
--   npm run db:migrate && npm run cf:migrations:sync

-- CreateTable
CREATE TABLE "ScreeningRequest" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "organizationId" TEXT NOT NULL,
    "applicationId" TEXT NOT NULL,
    "wantCredit" BOOLEAN NOT NULL DEFAULT true,
    "wantBackground" BOOLEAN NOT NULL DEFAULT true,
    "wantEviction" BOOLEAN NOT NULL DEFAULT true,
    "status" TEXT NOT NULL DEFAULT 'AWAITING_CONSENT',
    "consentToken" TEXT NOT NULL,
    "consentGivenAt" DATETIME,
    "consentDeclinedAt" DATETIME,
    "consentIpAddress" TEXT,
    "consentUserAgent" TEXT,
    "provider" TEXT NOT NULL DEFAULT 'manual',
    "resultSummary" TEXT,
    "reportUrl" TEXT,
    "completedAt" DATETIME,
    "completedById" TEXT,
    "requestedById" TEXT,
    "requestedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "ScreeningRequest_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "Organization" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ScreeningRequest_applicationId_fkey" FOREIGN KEY ("applicationId") REFERENCES "Application" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "ScreeningRequest_completedById_fkey" FOREIGN KEY ("completedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT "ScreeningRequest_requestedById_fkey" FOREIGN KEY ("requestedById") REFERENCES "User" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "ScreeningRequest_consentToken_key" ON "ScreeningRequest"("consentToken");

-- CreateIndex
CREATE INDEX "ScreeningRequest_organizationId_status_idx" ON "ScreeningRequest"("organizationId", "status");

-- CreateIndex
CREATE INDEX "ScreeningRequest_applicationId_idx" ON "ScreeningRequest"("applicationId");
