-- Generated by scripts/sync-d1-migrations.mjs from
--   prisma/migrations/20260831135455_photos_to_r2/migration.sql
-- Do not edit this file. Edit prisma/schema.prisma and run
--   npm run db:migrate && npm run cf:migrations:sync

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_ListingPhoto" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "listingId" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "data" BLOB,
    "storageKey" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "ListingPhoto_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "Listing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_ListingPhoto" ("contentType", "createdAt", "data", "filename", "id", "listingId", "sizeBytes", "sortOrder") SELECT "contentType", "createdAt", "data", "filename", "id", "listingId", "sizeBytes", "sortOrder" FROM "ListingPhoto";
DROP TABLE "ListingPhoto";
ALTER TABLE "new_ListingPhoto" RENAME TO "ListingPhoto";
CREATE UNIQUE INDEX "ListingPhoto_storageKey_key" ON "ListingPhoto"("storageKey");
CREATE INDEX "ListingPhoto_listingId_idx" ON "ListingPhoto"("listingId");
CREATE TABLE "new_MaintenancePhoto" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "requestId" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "contentType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "data" BLOB,
    "storageKey" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "MaintenancePhoto_requestId_fkey" FOREIGN KEY ("requestId") REFERENCES "MaintenanceRequest" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
INSERT INTO "new_MaintenancePhoto" ("contentType", "createdAt", "data", "filename", "id", "requestId", "sizeBytes") SELECT "contentType", "createdAt", "data", "filename", "id", "requestId", "sizeBytes" FROM "MaintenancePhoto";
DROP TABLE "MaintenancePhoto";
ALTER TABLE "new_MaintenancePhoto" RENAME TO "MaintenancePhoto";
CREATE UNIQUE INDEX "MaintenancePhoto_storageKey_key" ON "MaintenancePhoto"("storageKey");
CREATE INDEX "MaintenancePhoto_requestId_idx" ON "MaintenancePhoto"("requestId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
